Arewa Data Science Academy

Deep Learning Cohort2.0

Name: Kaloma Usman Majikumna


In [1]:
import torch

In [2]:
#2 Create a random tensor with shape (7, 7).
# Creating my random tensor
random_tensor = torch.rand(7, 7)

In [3]:
#diplaying my tensor
random_tensor

tensor([[9.0459e-01, 6.1551e-02, 6.0653e-01, 5.7977e-01, 2.0673e-01, 8.9263e-01,
         7.2410e-02],
        [3.5866e-02, 3.0752e-01, 1.1308e-01, 2.2616e-01, 8.1347e-01, 3.9705e-01,
         3.7121e-01],
        [5.5979e-01, 1.2470e-01, 1.8732e-01, 6.0610e-01, 1.0564e-01, 1.2324e-01,
         1.5925e-01],
        [3.0823e-01, 7.8159e-01, 6.7143e-01, 6.5205e-02, 5.8866e-04, 1.2449e-01,
         4.1684e-01],
        [6.7937e-01, 6.0610e-01, 5.1589e-01, 1.4813e-01, 8.3937e-01, 9.1945e-01,
         2.9309e-01],
        [7.6209e-01, 7.3545e-01, 8.9855e-02, 9.6842e-01, 1.2888e-01, 1.7882e-01,
         3.4724e-01],
        [5.0335e-01, 1.8511e-01, 7.0827e-01, 1.0602e-01, 2.3649e-01, 3.9617e-02,
         9.8467e-01]])

In [4]:
# Create the second random tensor called random_tensor2
random_tensor2 = torch.rand(1, 7)
random_tensor2

tensor([[0.0414, 0.1297, 0.7530, 0.0535, 0.7813, 0.0684, 0.9806]])

In [5]:
 # Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)#
 #Transpose of second matrix
 random_Tensor_transpose = random_tensor2.t()
 Matrix_multi = torch.mm(random_tensor, random_Tensor_transpose)
Matrix_multi

tensor([[0.8268],
        [1.1653],
        [0.4600],
        [1.0409],
        [1.5092],
        [0.6998],
        [1.7369]])

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensorA = torch.rand(7, 7)
random_tensorB = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.mm(random_tensorA, random_tensorB.t())
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [7]:
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)  # If using multi-GPU

In [8]:
#If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)
torch.cuda.manual_seed_all(1234)  # If using multi-GPU

In [9]:
#5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
#Create two random tensors of shape (2,3)
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)


In [10]:
# Move tensors to GPU (if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create random tensors
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

# Move tensors to GPU (if available)
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

# Print the tensors
print(tensor1)
print(tensor2)

tensor([[0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143]])
tensor([[0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872]])


In [11]:
#7. Matrix multiplication
print(tensor1.size())
print(tensor2.size())
print(" ")
Matrix_multi2 = torch.mm(tensor1, tensor1.t()) #Transpose the matrix and then multiply
print(Matrix_multi2, Matrix_multi2.shape)

torch.Size([2, 3])
torch.Size([2, 3])
 
tensor([[1.6301, 1.0441],
        [1.0441, 1.4214]]) torch.Size([2, 2])


In [12]:
#8. Find the maximum and minimum values of the output of 7

max_value = Matrix_multi2.max()
min_value = Matrix_multi2.min()
print("Max value: ",max_value)
print("Min value: ",min_value)


Max value:  tensor(1.6301)
Min value:  tensor(1.0441)


In [13]:

max_index = Matrix_multi2.argmax()  # Index of the maximum
min_index = Matrix_multi2.argmin()  # Index of the minimum

print("Max Index: ",max_index)
print("Min Index: ",min_index)

Max Index:  tensor(0)
Min Index:  tensor(1)


In [14]:


# Set the random seed for reproducibility
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
random_tensor = torch.rand(1, 1, 1, 10)

#all the 1 dimensions removed
squeezed_tensor = random_tensor.squeeze()

# Print the first tensor and its shape
print("Original Tensor:")
print(random_tensor)
print("Shape of Original Tensor:", random_tensor.shape)

# Print the second tensor (after squeezing) and its shape
print("\nSqueezed Tensor:")
print(squeezed_tensor)
print("Shape of Squeezed Tensor:", squeezed_tensor.shape)


Original Tensor:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of Original Tensor: torch.Size([1, 1, 1, 10])

Squeezed Tensor:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of Squeezed Tensor: torch.Size([10])


In [15]:
!git clone https://github.com/arewadataScience/ArewaDS-Deep-Learning.git

Cloning into 'ArewaDS-Deep-Learning'...
remote: Enumerating objects: 307, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 307 (delta 82), reused 39 (delta 39), pack-reused 213 (from 2)
Receiving objects: 100% (307/307), 11.65 MiB | 25.17 MiB/s, done.
Resolving deltas: 100% (151/151), done.
